Task 2: Arithmetic Practice 
1. Add two arrays 
2. Multiply arrays 
3. Divide arrays 

In [1]:
import numpy as np
arr_1 = np.array([[1,2,3],[4,5,6]])
arr_2 = np.array([[2,4,6],[8,9,10]])
print("Addition: ", arr_1+arr_2)
print("Multiplication: ", arr_1*arr_2)
print("Division: ", arr_1/arr_2)

Addition:  [[ 3  6  9]
 [12 14 16]]
Multiplication:  [[ 2  8 18]
 [32 45 60]]
Division:  [[0.5        0.5        0.5       ]
 [0.5        0.55555556 0.6       ]]


Task 3: Scalar Operations 
1. Add constant to array 
2. Multiply array 
3. Subtract constant 

In [2]:
a = np.array([[[2,4,6],[1,2,3],[2,3,1]]])
print ("add constant: ", a+2)
print ("multiply constant: ", a*10)
print ("subtract constant: ", a-3)

add constant:  [[[4 6 8]
  [3 4 5]
  [4 5 3]]]
multiply constant:  [[[20 40 60]
  [10 20 30]
  [20 30 10]]]
subtract constant:  [[[-1  1  3]
  [-2 -1  0]
  [-1  0 -2]]]


Task 4: Math Functions 
1. Find square root 
2. Find log values 
3. Round values 

In [7]:
b = np.array([25,49,36,81])
print("square root: ", np.sqrt(b))
print("log values: ", np.log(b))
c = np.array([1.2, 2.7, 3.5])
print("rounded:", np.round(c))

square root:  [5. 7. 6. 9.]
log values:  [3.21887582 3.8918203  3.58351894 4.39444915]
rounded: [1. 3. 4.]


Task 5: Aggregation 

1. Find sum 
2. Find mean 
3. Find max and min 

In [4]:
arr = np.array([[10, 20],[30, 40]]) 
print("sum: ", np.sum(arr)) 
print("mean: ", np.mean(arr)) 
print("max: ", np.max(arr)) 
print("min: ", np.min(arr)) 

sum:  100
mean:  25.0
max:  40
min:  10


Task 6: Axis Practice 
1. Row-wise sum 
2. Column-wise sum 

In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# 1. Row-wise sum 
print("Row-wise sum:", np.sum(a, axis=1))

# 2. Column-wise sum 
print("Column-wise sum:", np.sum(a, axis=0))

Row-wise sum: [ 6 15]
Column-wise sum: [5 7 9]


Task 7: Filtering 
1. Filter values > 20 
2. Filter even numbers 

 

In [6]:
a = np.array([10,20,30,40,50,60,70,80,90,100])
print("values greater than 50 : ", a[a>50])
print("even numbers : ", a[a%2==0])

values greater than 50 :  [ 60  70  80  90 100]
even numbers :  [ 10  20  30  40  50  60  70  80  90 100]
