### Task 2: Reshape Practice 
1. Convert 1D → 2D 
2. Convert 1D → 3D 
3. Try invalid reshape 

In [2]:
import numpy as np
arr_1 = np.array([10,20,30,40,50,60])
print("2D array:", arr_1.reshape(2,3))
print("3D array:", arr_1.reshape(1,3,2))

2D array: [[10 20 30]
 [40 50 60]]
3D array: [[[10 20]
  [30 40]
  [50 60]]]


In [3]:
#invalid reshape
print(arr_1.reshape(4,2))

ValueError: cannot reshape array of size 6 into shape (4,2)

### Task 3: Flatten 
1. Convert 2D → 1D 
2. Compare flatten vs ravel 

In [4]:
#2D --> 1D
arr_2 = np.array([[2,4,6],
                  [8,10,12]])
print("1D array:", arr_2.flatten())

1D array: [ 2  4  6  8 10 12]


In [18]:
print("ravel:", arr_2.ravel())

ravel: [ 2  4  6  8 10 12]


In [20]:
#compare flatten vs ravel
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
flat = matrix.flatten()
print("\nFlattened Array:")
print(flat)
ravel_arr = matrix.ravel()


print("\nFlatten vs Ravel:")
print("flatten():", flat)
print("ravel():", ravel_arr)

# Modify original matrix
matrix[0, 0] = 100

print("\nAfter modifying original matrix:")
print("Original Matrix:")
print(matrix)

print("flatten() result:")
print(flat)      # unchanged copy

print("ravel() result:")
print(ravel_arr) # changed view



Flattened Array:
[1 2 3 4 5 6]

Flatten vs Ravel:
flatten(): [1 2 3 4 5 6]
ravel(): [1 2 3 4 5 6]

After modifying original matrix:
Original Matrix:
[[100   2   3]
 [  4   5   6]]
flatten() result:
[1 2 3 4 5 6]
ravel() result:
[100   2   3   4   5   6]


### Task 4: Transpose 
1. Transpose matrix 
2. Verify rows   columns 

In [23]:
# transpose matrix
arr_3 = np.array([[1,2],[3,4],
                [5,6],[7,8]])
print("array:", arr_3)
print("transpose:", arr_3.T)
print("original shape:", arr_3.shape)
print("transposed shape:",arr_3.T.shape)

array: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
transpose: [[1 3 5 7]
 [2 4 6 8]]
original shape: (4, 2)
transposed shape: (2, 4)


### Task 5: Stacking 
1. Vertical stack 
2. Horizontal stack 
3. Combine arrays 

In [26]:
a = np.array([1,2])
b = np.array([6,7])
print("v stack:", np.vstack((a, b))) 
print("h stack:", np.hstack((a, b))) 
print("combined array:", np.concatenate((a,b)))

v stack: [[1 2]
 [6 7]]
h stack: [1 2 6 7]
combined array: [1 2 6 7]


### Task 6: Splitting 
1. Split array 
2. Split rows 

In [15]:
a = np.array([[2,4],[6,8],[10,12],[14,16]])
print(np.split(a,2))

[array([[2, 4],
       [6, 8]]), array([[10, 12],
       [14, 16]])]


In [17]:
print("row split:",np.vsplit(a, 4))


row split: [array([[2, 4]]), array([[6, 8]]), array([[10, 12]]), array([[14, 16]])]
