### Task 2: Random Integer Practice 
1. Generate random integer 
2. Generate array of integers 
3. Create random matrix 

In [1]:
import numpy as np
#generate random integer
print(np.random.randint(1,20))

18


In [2]:
#generate array of integers
arr_1 =np.random.randint(10,50,size = 10)
print(arr_1)

[19 33 46 22 21 32 27 37 27 12]


In [3]:
#create random matrix
a = np.random.randint(1,10, size=(3,2))
print(a)

[[1 3]
 [2 1]
 [4 7]]


### Task 3: Random Decimal Practice 
1. Generate decimal values 
2. Create 2D decimal matrix 

In [4]:
#generate random decimal values
b = np.random.rand()
print(b)

0.5799390893794764


In [5]:
#create 2D decimal matrix
d = np.random.rand(2,2)
print(d)

[[0.65555638 0.09401835]
 [0.35975993 0.4769087 ]]


### Task 4: Random Choice 
1. Pick random color 
2. Generate multiple choices 
3. Simulate random names 

In [ ]:
color = ["red", "blue", "orange","green", "yellow", "violet", "black", "white", "brown"]
#pick random color
choice_1 = np.random.choice(color)
#generate multiple choices
choice_2 = np.random.choice(color, size=4)
choice_3 = np.random.choice(color, size= 7)
choice_4 = np.random.choice(color, size= 10)
print("choice 1:", choice_1)
print("choice 2:", choice_2)
print("choice 3:", choice_3)
print("choice 4:", choice_4)

choice 1: white
choice 2: ['yellow' 'red' 'orange' 'violet']
choice 3: ['white' 'black' 'white' 'blue' 'black' 'red' 'green']
choice 4: ['red' 'violet' 'orange' 'green' 'blue' 'green' 'yellow' 'orange' 'black'
 'black']


In [ ]:
#simulate random names
names = ["Meera", "Anagha", "Sreehari", "Adithya","Geethu","Akhil","Aswin","Vishnu", "Sachin", "Sreya"]
list_1 = np.random.choice(names, size=5)
list_2 = np.random.choice(names, size=10)
print("list 1:", list_1)
print("list 2:", list_2)

list 1: ['Sreehari' 'Vishnu' 'Adithya' 'Akhil' 'Meera']
list 2: ['Geethu' 'Sreya' 'Anagha' 'Aswin' 'Sachin' 'Adithya' 'Adithya' 'Vishnu'
 'Geethu' 'Sreya']


### Task 5: Shuffle 
1. Shuffle array 
2. Shuffle student IDs 

In [8]:
arr_1 = np.array([20,25,30,35,40,45,50,55,60])
print("array:", arr_1)
#shuffle array
np.random.shuffle(arr_1)
print("shuffled array:", arr_1)

array: [20 25 30 35 40 45 50 55 60]
shuffled array: [50 25 20 45 30 60 40 35 55]


In [10]:
student_ids = np.array([101, 102, 103, 104, 105])
#shuffle student IDs
np.random.shuffle(student_ids)
print("Shuffled Student IDs:", student_ids)

Shuffled Student IDs: [103 101 105 104 102]


### Task 6: Dataset Simulation 
1. Create marks dataset 
2. Create attendance dataset 
3. Create random image matrix

In [ ]:
#create marks dataset
marks = np.random.randint(45,100, size=(10,3))
print(marks)

[[55 77 91]
 [69 50 58]
 [62 86 60]
 [45 68 63]
 [47 59 76]
 [57 81 70]
 [93 69 89]
 [86 89 78]
 [71 66 64]
 [65 48 71]]


In [13]:
#create attendance sheet
#5 working days ,1-present, 0-absent
attendance = np.random.choice([0,1], size=(10,5))
print(attendance)

[[0 1 1 1 1]
 [0 1 0 1 1]
 [0 1 0 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 1 0]
 [1 1 0 1 0]
 [0 0 1 0 1]
 [0 0 1 1 0]
 [1 1 1 1 1]]


In [14]:
#create random image matrix
image_matrix = np.random.randint(0, 256, size=(4, 4))
print(image_matrix)

[[197 183  67 205]
 [102 105 135  56]
 [ 31  45  71 110]
 [187  72  32  17]]
