### Task 2: Array Creation 
1. Create 1D array 
2. Create 2D array 
3. Create 3D array 
4. Print all 

In [2]:
import numpy as np
#1D array
arr_1 = np.array([5,10,15,20])
print("1D: ", arr_1)
#2D array
arr_2 = np.array([[5,10],[15,20]])
print("2D: ", arr_2)
arr_3 = np.array([
    [[5, 10], [15, 20]],
    [[25, 30], [35, 40]]
])
print("3D: ",arr_3)

1D:  [ 5 10 15 20]
2D:  [[ 5 10]
 [15 20]]
3D:  [[[ 5 10]
  [15 20]]

 [[25 30]
  [35 40]]]


### Task 3: Properties 
1. Print shape 
2. Print dimensions 
3. Print data type 

In [4]:
print("Shape:", arr_3.shape)
print("Dimensions:", arr_3.ndim)
print("Data type:", arr_3.dtype)

Shape: (2, 2, 2)
Dimensions: 3
Data type: int32


### Task 4: Special Arrays 
1. Create zero matrix 
2. Create ones matrix 
3. Create identity matrix 
4. Create range array 

In [5]:
# Zero matrix
zeros = np.zeros((3, 3))

# Ones matrix
ones = np.ones((2, 2))

# Identity matrix
identity = np.eye(3)

# Range array
range_arr = np.arange(0, 10)

print(zeros)
print(ones)
print(identity)
print(range_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2 3 4 5 6 7 8 9]


### Task 5: Indexing 
1. Access first element 
2. Slice array 
3. Access element in 2D 

In [11]:
arr = np.array([10, 20, 30, 40])

# Access first element
print(arr[0])

# Slice array
print(arr[1:3])

# Access element in 2D
arr2 = np.array([[1, 2], [3, 4]])
print(arr2[0, 1])  

10
[20 30]
2


### Task 6: Reshaping 
1. Convert 1D → 2D 
2. Convert 2D → 1D 

In [12]:
# Convert 1D → 2D
arr = np.array([1, 2, 3, 4])
arr_2d = arr.reshape(2, 2)
print(arr_2d)

# Convert 2D → 1D
arr_1d = arr_2d.reshape(-1)
print(arr_1d)

[[1 2]
 [3 4]]
[1 2 3 4]
