### Task 2: 1D Practice 
1. Access first element 
2. Access last element 
3. Slice array 

In [2]:
import numpy as np
arr = np.array([2,4,6,8,10])
print("first element: ",arr[0])
print("last element: ",arr[-1])
print("sliced array: ",arr[1:4])

first element:  2
last element:  10
sliced array:  [4 6 8]


### Task 3: 2D Practice 
1. Access element 
2. Print row 
3. Print column 

In [3]:
arr_2 =np.array([[1,2],[3,4]])
#access element
print(arr_2[0][1])
print(arr_2[1,0])
#print row
print("first row: ", arr_2[0]) 
#print column
print("second column: ", arr_2[:,1]) 

2
3
first row:  [1 2]
second column:  [2 4]


### Task 4: 3D Practice 

1. Access layer 
2. Access row inside layer 
3. Access single element 

In [4]:
arr_3 = np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]]])
print("shape: ",arr_3.shape)
print("layer 1: ",arr_3[0])
print("layer 2 : ", arr_3[1])

print("row 2 inside layer 1:",arr_3[0][1])
print("row 2 inside layer 2: ",arr_3[1][1])
print("element inside  row 2 of layer 2: ",arr_3[1][1][1])

shape:  (2, 2, 3)
layer 1:  [[1 2 3]
 [4 5 6]]
layer 2 :  [[ 7  8  9]
 [10 11 12]]
row 2 inside layer 1: [4 5 6]
row 2 inside layer 2:  [10 11 12]
element inside  row 2 of layer 2:  11


### Task 5: Slicing 
1. Extract sub-array 
2. Use step slicing 
3. Slice rows and columns 

In [5]:
# for 1d array
arr_1 = np.array([1,2,3,4,5,6])
#Extract sub-array with step
print(arr_1[1:6:2])

[2 4 6]


In [7]:
# for 2d array
arr_2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
#Extract sub-array 
print("sub-array: ", arr_2[1:3,0:2])
#Step slicing
print("step slicing: ", arr_2[:,::2])
#Slice rows and columns 
print("row 1:", arr_2[0,:])
print("column 2:", arr_2[:,1])

sub-array:  [[4 5]
 [7 8]]
step slicing:  [[1 3]
 [4 6]
 [7 9]]
row 1: [1 2 3]
column 2: [2 5 8]


In [8]:
#for 3d array
arr_3 = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]],
                  [[13,14,15],[16,17,18]]])
#sub-array
print("sub-array: ", arr_3[0:2,:,1:3])
#Step slicing
print("step slicing: ", arr_3[:,:,::2])
#Slice rows and columns 
print("row 2 of layer 2: ", arr_3[1:2,1,:])
print("first 2 columns of layer 2:", arr_3[1, :, 0:2])

sub-array:  [[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]
step slicing:  [[[ 1  3]
  [ 4  6]]

 [[ 7  9]
  [10 12]]

 [[13 15]
  [16 18]]]
row 2 of layer 2:  [[10 11 12]]
first 2 columns of layer 2: [[ 7  8]
 [10 11]]


### Task 6: Boolean Indexing 
1. Filter values > 25 
2. Filter values between range 
3. Replace values conditionally 

In [30]:
arr = np.array([10,20,30,40,50,60,70])
print("values > 25: ",arr[arr>25])
print("values btw 25 and 50: ", arr[(arr>25)& (arr<50)])
#replace values
arr[arr<30]=0
print(arr)

values > 25:  [30 40 50 60 70]
values btw 25 and 50:  [30 40]
[ 0  0 30 40 50 60 70]
