### Task 2: Marks Analysis 
1. Find average marks 
2. Find highest marks 
3. Find lowest marks 
4. Find topper 

In [2]:
import numpy as np
marks =np.array([[75,64,80],
        [67,56,72],
        [87,72,70]])
print("average mark:", np.mean(marks))
print("highest marks:", np.max(marks))
print("lowest marks:", np.min(marks))
total = np.sum(marks, axis =1)
print("topper index:", np.argmax(total))

average mark: 71.44444444444444
highest marks: 87
lowest marks: 56
topper index: 2


### Task 3: Image Operations 
1. Increase brightness 
2. Decrease brightness 
3. Normalize image pixels 

In [3]:
image = np.array([[100,110,150],
                  [200,230,250],
                  [300,320,350]])
print("bright:", image+50)
print("dark:", image-50)
print("normalized:", image/np.max(image))

bright: [[150 160 200]
 [250 280 300]
 [350 370 400]]
dark: [[ 50  60 100]
 [150 180 200]
 [250 270 300]]
normalized: [[0.28571429 0.31428571 0.42857143]
 [0.57142857 0.65714286 0.71428571]
 [0.85714286 0.91428571 1.        ]]


### Task 4: Dataset Filtering 
1. Filter values > 50 
2. Replace low values 
3. Count filtered values 

In [ ]:
arr_1 = np.array([12,18,9,45,34,82,35,45,78,56,69,98,32,37])
filtered = arr_1[arr_1>50]
print("filtered values:", filtered)
arr_1[arr_1<50]=0
print("replaced array:", arr_1)
print("count of values>50:",np.sum(arr_1>50))

filtered values: [82 78 56 69 98]
replaced array: [ 0  0  0  0  0 82  0  0 78 56 69 98  0  0]
count of values>50: 5


### Task 5: Reshaping 
1. Convert 1D → 2D 
2. Convert 2D → 1D 
3. Create 3D dataset 

In [7]:
arr_1d = np.array([2,4,6,8,10,12])
arr_2d = arr_1d.reshape(2,3)
print("2D array:\n", arr_2d)
back_1d = arr_2d.flatten()
print("1D array:", back_1d)
arr_3d = np.array([[[1,2,3],[4,5,6]]])
print("3D array:\n", arr_3d)

2D array:
 [[ 2  4  6]
 [ 8 10 12]]
1D array: [ 2  4  6  8 10 12]
3D array:
 [[[1 2 3]
  [4 5 6]]]


### Task 6: Dataset Simulation 
1. Attendance matrix 
2. Marks dataset 
3. Weather dataset 

In [9]:
attendance = np.random.randint(0,2, size=(10,5)) #10 students, 5 working days
print("attendance matrix:\n", attendance)

attendance matrix:
 [[0 0 1 0 1]
 [0 0 1 1 0]
 [1 1 1 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 1 1 1 0]
 [0 1 1 1 1]
 [0 1 1 0 1]
 [0 1 1 1 0]
 [0 1 0 1 1]]


In [ ]:
marks = np.random.randint(0,101, size =(5,4)) # 5 students , 4 subjects
print("marks matrix:\n", marks)

marks matrix:
 [[22 60 36 35]
 [27 33 95 90]
 [95 10 93 50]
 [25 27 12 94]
 [ 2 77 45 58]]


In [19]:
#temperature: 20C-->40C , rain fall:0 --> 20 mm and 7 days
weather = np.random.uniform(
    low=[20, 0],
    high=[40, 20],
    size=(7, 2)
)
print("weather data:",weather)

weather data: [[32.54276751 18.27731029]
 [25.04750729  7.67773306]
 [36.7072662  12.97549504]
 [34.84480693 16.15899328]
 [24.0830755   8.87096761]
 [27.02451339  3.26597212]
 [38.4561932  15.98924002]]
