### Task 2: Basic Broadcasting 
1. Add scalar to array 
2. Multiply array with scalar 
3. Divide array by scalar 

In [1]:
# add scalar to array
import numpy as np
a = np.array([11,22,33,44,55])
print("add :", a+10)
print("multiply :", a*10)
print("divide :", a/11)

add : [21 32 43 54 65]
multiply : [110 220 330 440 550]
divide : [1. 2. 3. 4. 5.]


### Task 3: Array Broadcasting 
1. Add two compatible arrays 
2. Multiply arrays 
3. Observe shape changes 

In [8]:
b = np.array([[1,2],[3,4],[5,6]])
c = np.array([[2],[6],[8]])
print("b's shape:", b.shape)
print("c's shape:", c.shape)
add_bc = b+c
multiply_bc = b*c
print("addition: ",add_bc,"\nshape:", add_bc.shape)
print("multiplication:",multiply_bc,"\nshape:", multiply_bc.shape)

b's shape: (3, 2)
c's shape: (3, 1)
addition:  [[ 3  4]
 [ 9 10]
 [13 14]] 
shape: (3, 2)
multiplication: [[ 2  4]
 [18 24]
 [40 48]] 
shape: (3, 2)


### Task 4: Shape Practice 
1. Print shapes 
2. Check compatible shapes 
3. Try incompatible shapes 

In [ ]:
#compatible dimensions
b = np.array([[1,2,3],[4,5,6]])
c = np.array([2,6,8])
print(b.shape)
print(c.shape)
add_bc = b+c
multiply_bc = b*c
print("addition: ",add_bc,"\nshape:",add_bc.shape)
print("multiplication:",multiply_bc,"\nshape:",multiply_bc.shape)

(2, 3)
(3,)
addition:  [[ 3  8 11]
 [ 6 11 14]] 
shape: (2, 3)
multiplication: [[ 2 12 24]
 [ 8 30 48]] 
shape: (2, 3)


In [14]:
#incompatible dimensions
b = np.array([[1,2,3],[4,5,6]])
c = np.array([2,6,8,9])
print(b+c)
print(b*c)



ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

### Task 5: 2D Broadcasting 
1. Add scalar to matrix 
2. Multiply matrix 
3. Normalize matrix values 

In [18]:
arr_1 = np.array([[10,20,30],[40,50,60]])
print("addition:", arr_1 + 4)
print("multiplication:", arr_1*10)

addition: [[14 24 34]
 [44 54 64]]
multiplication: [[100 200 300]
 [400 500 600]]


In [21]:
normalized = (arr_1 - arr_1.min()) / (arr_1.max() - arr_1.min())

print("\nNormalized Matrix:\n", normalized)


Normalized Matrix:
 [[0.  0.2 0.4]
 [0.6 0.8 1. ]]
